<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content>
        <meta name="author" content="Денис Шевченко">
        <link rel="icon" href="../../static/images/favicon.ico">

        <title>Обработка исключений</title>

        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

        <link href="../../static/css/default.css" rel="stylesheet">
        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

        <script>
          window.___gcfg = {
            lang: 'ru'
          };
        </script>

        <script src="https://apis.google.com/js/platform.js" async defer>
        </script>
    </head>

  <body>
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <div id="logo">
                <a class="navbar-brand" href="../../ru/index.html" title="Домой">
                  О Haskell по-человечески
                </a>
              </div>
            </div>
            
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="../../ru/chapters.html" target="_blank">Оглавление</a></li>
              </ul>
            </div>
          </div>
        </nav>

        <div id="content">
            <h1>Обработка исключений</h1>

            <p>Мы все стремимся создавать программные системы, свободные от ошибок. И всё же иногда они появляются, а значит, нам приходится иметь с ними дело. Поговорим об исключениях, тем более что знать о них необходимо: многие пакеты из Hackage содержат код, кидающийся этими самыми исключениями.</p>
<p>Прежде всего, нам понадобится модуль <code>Control.Exception</code>:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="kw">import </span><span class="dt">Control.Exception</span></code></pre>
<p>Этот стандартный модуль предназначен для кидания и ловли исключений, причём как стандартных, так и наших собственных. Важно отметить: мы можем бросить исключение как из чистых функций, так и из функций с побочными эффектами, однако поймать его в чистой функции мы не сможем.</p>
<h2 id="проблема-с-файлом">Проблема с файлом</h2>
<p>Чаще всего мы будем сталкиваться с исключениями, брошенными из функций, взаимодействующих с внешним миром. Канонический пример: мы хотим прочесть содержимое файла, который отсутствует:</p>
<pre class="haskell "><code>main :: IO ()
main = do
    fileContent &lt;- readFile &quot;Users/shevchenko/test.c&quot;  -- Неверный путь...
    putStrLn fileContent</code></pre>
<p>Вывод будет таким:</p>
<pre class="sourceCode bash"><code class="sourceCode bash"><span class="kw">Real</span>: Users/shevchenko/test.c: openFile: does not exist (No such file or directory)</code></pre>
<p>Функция <code>readFile</code> бросила исключение, ведь сообщить о проблеме с файлом она может только так. Исключение, не найдя преград на своём пути, было поймано уже на самом верхнем уровне приложения, после чего сообщение об ошибке было выведено нам, а само приложение скоропостижно скончалось.</p>
<h2 id="ловим">Ловим</h2>
<p>Итак:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="kw">import </span><span class="dt">Control.Exception</span> 

<span class="ot">tryToOpenFile ::</span> FilePath <span class="ot">-&gt;</span> <span class="dt">IO</span> <span class="dt">String</span>
tryToOpenFile path <span class="fu">=</span>
    readFile path <span class="ot">`catch`</span> possibleErrors
    where
        <span class="ot">possibleErrors ::</span> <span class="dt">IOException</span> <span class="ot">-&gt;</span> <span class="dt">IO</span> <span class="dt">String</span>
        possibleErrors error <span class="fu">=</span> return <span class="fu">$</span> show error

<span class="ot">main ::</span> <span class="dt">IO</span> ()
main <span class="fu">=</span> <span class="kw">do</span>
    fileContent <span class="ot">&lt;-</span> tryToOpenFile <span class="st">&quot;Users/shevchenko/test.c&quot;</span>
    putStrLn fileContent</code></pre>
<p>Теперь у нас есть функция <code>tryToOpenFile</code>, которая открывает файл по заданному пути, но делает это осторожно, используя функцию <code>catch</code>. Как вы уже поняли, функция catch, определённая в модуле <code>Control.Exception</code>, умеет ловить исключения. Вот её объявление:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell">catch<span class="ot"> ::</span> <span class="dt">Exception</span> e <span class="ot">=&gt;</span> <span class="dt">IO</span> a <span class="ot">-&gt;</span> (e <span class="ot">-&gt;</span> <span class="dt">IO</span> a) <span class="ot">-&gt;</span> <span class="dt">IO</span> a</code></pre>
<p>Функция принимает два аргумента: первым идёт <code>IO</code>-действие, вторым идёт функция-обработчик. Если действие бросило исключение, отражённое полиморфным типом <code>e</code>, это исключение будет передано обработчику.</p>
<p>Обратите внимание: тип исключения входит в контекст класса Exception, определённого в том же модуле <code>Control.Exception</code>. Любое исключение в вашем приложении обязано входить в контекст этого класса.</p>
<p>Для большей читабельности мы используем инфиксную запись функции <code>catch</code>, с которой гармонирует имя нашего обработчика:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell">readFile path <span class="ot">`catch`</span> possibleErrors</code></pre>
<p>Если при чтении файла возникла проблема, соответствующее исключение поступает на вход нашего обработчика:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="ot">possibleErrors ::</span> <span class="dt">IOException</span> <span class="ot">-&gt;</span> <span class="dt">IO</span> <span class="dt">String</span>
possibleErrors error <span class="fu">=</span> return <span class="fu">$</span> show error</code></pre>
<p>Обработчик принимает значение типа <code>IOException</code>. В теле обработчика мы стрингифицируем полученное исключение, а затем готовую строку, содержащую описание произошедшей ошибки, заворачиваем в действие <code>IO String</code>. Если же нас не устраивает уже имеющееся сообщение об ошибке - предоставим своё:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell">possibleErrors error <span class="fu">=</span> return <span class="st">&quot;Unable to open this file. Please check it.&quot;</span></code></pre>
<p>Это сообщение и будет выведено на экран в случае возникновения проблемы.</p>
<h2 id="ловим-наоборот">Ловим наоборот</h2>
<p>Перепишем нашу функцию:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="ot">tryToOpenFile ::</span> FilePath <span class="ot">-&gt;</span> <span class="dt">IO</span> <span class="dt">String</span>
tryToOpenFile path <span class="fu">=</span>
    handle possibleErrors (readFile path)  <span class="co">-- То же самое, но наоборот.</span>
    where
        <span class="ot">possibleErrors ::</span> <span class="dt">IOException</span> <span class="ot">-&gt;</span> <span class="dt">IO</span> <span class="dt">String</span>
        possibleErrors error <span class="fu">=</span> return <span class="st">&quot;Aaaaa!!! Please check file.&quot;</span></code></pre>
<p>Мы заменили функцию <code>catch</code> на функцию <code>handle</code>. Никакой разницы между этими функциями нет, за исключением порядка следования аргументов: <code>catch</code> принимает обработчик вторым по счёту, а <code>handle</code> - первым. Таким образом, <code>catch</code> читабельнее в инфиксной форме, а <code>handle</code> - в простой. Так что выбирайте на вкус.</p>
<h2 id="пытаемся">Пытаемся</h2>
<p>Стандартная функция <code>try</code> использует иной подход. Вот пример:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="kw">import </span><span class="dt">Control.Exception</span>

<span class="ot">main ::</span> <span class="dt">IO</span> ()
main <span class="fu">=</span> <span class="kw">do</span>
    result <span class="ot">&lt;-</span> try <span class="fu">$</span> readFile<span class="ot"> path ::</span> <span class="dt">IO</span> (<span class="dt">Either</span> <span class="dt">IOException</span> <span class="dt">String</span>)
    case result <span class="kw">of</span>
        <span class="dt">Left</span> exception <span class="ot">-&gt;</span> putStrLn <span class="fu">$</span> <span class="st">&quot;Fault: &quot;</span> <span class="fu">++</span> show exception
        <span class="dt">Right</span> content <span class="ot">-&gt;</span> putStrLn content
    where path <span class="fu">=</span> <span class="st">&quot;Users/dshevchenko/test.c&quot;</span></code></pre>
<p>Разберём по полочкам.</p>
<p>Объявление функции <code>try</code> выглядит так:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="ot">try ::</span> <span class="dt">Exception</span> e <span class="ot">=&gt;</span> <span class="dt">IO</span> a <span class="ot">-&gt;</span> <span class="dt">IO</span> (<span class="dt">Either</span> e a)</code></pre>
<p>Эта функция принимает наше <code>IO</code>-действие, а возвращает другое <code>IO</code>-действие, которое в свою очередь возвращает значение стандартного типа <code>Either e a</code>. <code>Either</code> - это конструктор типа, предназначенный для хранения одного из двух значений, каждое из которых соответствует хорошему результату и плохому. Обратите внимание, мы явно указали тип значения, возвращённого функцией <code>try</code>:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell">try <span class="fu">$</span> readFile<span class="ot"> path ::</span> <span class="dt">IO</span> (<span class="dt">Either</span> <span class="dt">IOException</span> <span class="dt">String</span>)</code></pre>
<p>Мы сказали: “Пусть действие, возвращённое функцией <code>try</code>, вернёт нам значение типа <code>Either IOException String</code>, в котором будет лежать либо значение типа <code>IOException</code> (в случае, если при чтении файла что-то случилось), либо значение типа <code>String</code> с содержимым файла”.</p>
<p>Далее смотрим, получилось ли у нас:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="kw">case</span> result <span class="kw">of</span>
    <span class="dt">Left</span> exception <span class="ot">-&gt;</span> putStrLn <span class="fu">$</span> <span class="st">&quot;Fault: &quot;</span> <span class="fu">++</span> show exception
    <span class="dt">Right</span> content <span class="ot">-&gt;</span> putStrLn content</code></pre>
<p>Тип <code>Either</code> имеет два конструктора, <code>Left</code> и <code>Right</code>. В нашем случае это можно изобразить так:</p>
<pre><code>Either IOException String</code></pre>
<p>        |           |         Left        Right</p>
<p>Используя эти два конструктора, мы можем понять, что же произошло. Конструкция <code>case-of</code> поможет нам. Мы говорим: “Если <code>result</code> соответствует левому значению - это значение типа <code>IOException</code>. Что-то пошло не так, выводим исключение на экран! Ну а если <code>result</code> соответствует правому значению - перед нами <code>String</code>. Всё прошло успешно, выводим на экран содержимое прочитанного файла”.</p>
<h2 id="в-чистом-мире">В чистом мире</h2>
<p>Иногда нам нужно поймать исключение, брошенное из чистой функции. Например:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="kw">import </span><span class="dt">Control.Exception</span>

<span class="ot">main ::</span> <span class="dt">IO</span> ()
main <span class="fu">=</span> <span class="kw">do</span>
    result <span class="ot">&lt;-</span> try <span class="fu">$</span> <span class="dv">2</span> <span class="ot">`div`</span> <span class="dv">0</span><span class="ot"> ::</span> <span class="dt">IO</span> (<span class="dt">Either</span> <span class="dt">SomeException</span> <span class="dt">Integer</span>)
    case result <span class="kw">of</span>
        <span class="dt">Left</span> exception <span class="ot">-&gt;</span> putStrLn <span class="fu">$</span> <span class="st">&quot;Fault: &quot;</span> <span class="fu">++</span> show exception
        <span class="dt">Right</span> value <span class="ot">-&gt;</span> print value</code></pre>
<p>Здесь мы попытались проверить результат деления числа 2 на ноль. К сожалению, этот код не пройдёт компиляцию. Ведь функция <code>try</code> ожидает на вход <code>IO</code>-действие, однако стандартная функция <code>div</code> чиста и возвращает обыкновенное число. Следовательно, нам нужен маленький трюк:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="kw">import </span><span class="dt">Control.Exception</span>

<span class="ot">main ::</span> <span class="dt">IO</span> ()
main <span class="fu">=</span> <span class="kw">do</span>
    result <span class="ot">&lt;-</span> try <span class="fu">$</span> evaluate <span class="fu">$</span> <span class="dv">2</span> <span class="ot">`div`</span> <span class="dv">0</span>
                    <span class="ot">::</span> <span class="dt">IO</span> (<span class="dt">Either</span> <span class="dt">SomeException</span> <span class="dt">Integer</span>)
    case result <span class="kw">of</span>
        <span class="dt">Left</span> exception <span class="ot">-&gt;</span> putStrLn <span class="fu">$</span> <span class="st">&quot;Fault: &quot;</span> <span class="fu">++</span> show exception
        <span class="dt">Right</span> value <span class="ot">-&gt;</span> print value</code></pre>
<p>Мы обернули вызов функции <code>div</code> в стандартную функцию <code>evaluate</code>. Теперь всё скомпилируется, и при запуске мы получим ожидаемое нами гневное сообщение:</p>
<pre class="sourceCode bash"><code class="sourceCode bash"><span class="kw">Fault</span>: divide by zero</code></pre>
<p>Функция <code>evaluate</code> объявлена так:</p>
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="ot">evaluate ::</span> a <span class="ot">-&gt;</span> <span class="dt">IO</span> a</code></pre>
<p>Эта функция играет роль адаптера: она как бы превращает результат в <code>IO</code>-действие, возвращающее этот результат. И после того, как функция <code>div</code> вернула нам обыкновенное число, функция <code>evaluate</code> обернула это число в действие, ожидаемое функцией <code>try</code>.</p>
<h2 id="в-сухом-остатке">В сухом остатке</h2>
<ul>
<li>Исключение может быть брошено из любой функции, но обработать его мы сможем только в IO-функции.</li>
<li>Функция <code>catch</code> ловит исключение и передаёт его обработчику.</li>
<li>Функция <code>handle</code> - зеркальная сестра функции <code>catch</code>.</li>
<li>Функция <code>try</code> работает в сотрудничестве с конструктором типа <code>Either</code>. Анализируя порождённое этим типом значение, мы поймём, возникла ли проблема в интересующей нас функции, или всё прошло гладко.</li>
<li>Для работы с <code>try</code> чистую функцию следует поместить в <code>evaluate</code>-обёртку.</li>
</ul>
<p>Почти готово. Но наше рассмотрение исключений не было бы полным без изучения наших собственных исключений.</p>

<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div class="clear-button text-left">
            <div class="chapters-selector">
                <a href="../../ru/io/do-imperative-world.html" title="Предыдущая глава"><span class="fa fa-hand-o-left"></span></a>
            </div>
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div class="clear-button text-right">
            <div class="chapters-selector">
                <a href="../../ru/io/own-exceptions.html" title="Следующая глава"><span class="fa fa-hand-o-right"></span></a>
            </div>
        </div>
    </div>
</div>
<div style="padding-top: 40px;"><div>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'ohaskell'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
 

        </div> 

        <footer class="footer">
            Книга создана с помощью <strong><a href="http://jaspervdj.be/hakyll/" target="_blank">Hakyll</a></strong> и живёт на <strong><a href="https://github.com/denisshevchenko/ohaskell" target="_blank">GitHub</a></strong>.
            <div class="copyright-note">
                Исходный код сайта и содержимое книги распространяются на условиях <a href="https://github.com/denisshevchenko/ohaskell/blob/master/LICENSE" target="_blank">свободной лицензии MIT</a>.
            </div>
        </footer>
    </div>
  </body>
</html>


